/** AUTH */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const TOKEN_REFRESH_REQUEST = 'TOKEN_REFRESH_REQUEST';
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAILURE = 'TOKEN_REFRESH_FAILURE';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

/** EXAMPLES */

export const FETCH_EXAMPLES = 'FETCH_EXAMPLES';
export const FETCH_EXAMPLES_SUCCESS = 'FETCH_EXAMPLES_SUCCESS';
export const FETCH_EXAMPLES_FAILURE = 'FETCH_EXAMPLES_FAILURE';

export const ADD_EXAMPLE = 'ADD_EXAMPLE';
export const ADD_EXAMPLE_SUCCESS = 'ADD_EXAMPLE_SUCCESS';
export const ADD_EXAMPLE_FAILURE = 'ADD_EXAMPLE_FAILURE';

export const EDIT_EXAMPLE = 'EDIT_EXAMPLE';
export const EDIT_EXAMPLE_SUCCESS = 'EDIT_EXAMPLE_SUCCESS';
export const EDIT_EXAMPLE_FAILURE = 'EDIT_EXAMPLE_FAILURE';

export const DELETE_EXAMPLE = 'DELETE_EXAMPLE';
export const DELETE_EXAMPLE_SUCCESS = 'DELETE_EXAMPLE_SUCCESS';
export const DELETE_EXAMPLE_FAILURE = 'DELETE_EXAMPLE_FAILURE';